language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-26
node_js:
  - "8"
dist: trusty
cache:
  directories:
     - ./node_modules
before_install:
  - nvm install 8
  - nvm use 8
  - npm i -g cordova
script:
  - cordova platform add android
  - cordova build android -- --gradleArg=-PcdvMinSdkVersion=19
before_deploy:
  - cp platforms/android/build/outputs/apk/android-debug.apk xstrme-android-${TRAVIS_BRANCH}.apk
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: xstrme-android-*.apk
    skip_cleanup: true
    on:
      tags: true
