language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-19
node_js:
  - "8"
dist: trusty
cache:
  directories:
     - ./node_modules
before_install:
  - nvm install 8
  - nvm use 8
  - npm i -g cordova
script:
  - cordova platform add android
  - cordova build android --release -- --gradleArg=-PcdvMinSdkVersion=19
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: platforms/android/build/outputs/apk/android-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
